#!/bin/bash
## Disable Spotlight Suggestions
## Created by Justin S. Smith
## 2020-01-06

## Script the Installation of a Configuration Profile
## Create the .mobileconfig file in /private/tmp/
## security cms -D -i $INSTALL_PATH | xmllint --format -


## Variables

INSTALL_PATH="/private/tmp/config_profile.mobileconfig"

## Begin Installation

cat << EOF > $INSTALL_PATH
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>PayloadContent</key>
			<dict>
				<key>com.apple.lookup.shared</key>
				<dict>
					<key>Forced</key>
					<array>
						<dict>
							<key>mcx_preference_settings</key>
							<dict>
								<key>LookupSuggestionsDisabled</key>
								<true/>
							</dict>
						</dict>
					</array>
				</dict>
			</dict>
			<key>PayloadDescription</key>
			<string></string>
			<key>PayloadDisplayName</key>
			<string>Custom</string>
			<key>PayloadEnabled</key>
			<true/>
			<key>PayloadIdentifier</key>
			<string>14231ECF-B16D-40B0-B0C8-6D0B8E1CA9AA</string>
			<key>PayloadOrganization</key>
			<string>J.P. Morgan Chase &amp; Co.</string>
			<key>PayloadType</key>
			<string>com.apple.ManagedClient.preferences</string>
			<key>PayloadUUID</key>
			<string>14231ECF-B16D-40B0-B0C8-6D0B8E1CA9AA</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>PayloadDescription</key>
	<string></string>
	<key>PayloadDisplayName</key>
	<string>Disable Spotlight Suggestions</string>
	<key>PayloadEnabled</key>
	<true/>
	<key>PayloadIdentifier</key>
	<string>2F8264C0-36C1-424F-BE1F-32A3304ED137</string>
	<key>PayloadOrganization</key>
	<string>JPMorgan Chase</string>
	<key>PayloadRemovalDisallowed</key>
	<true/>
	<key>PayloadScope</key>
	<string>User</string>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>2F8264C0-36C1-424F-BE1F-32A3304ED137</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist>

EOF

## Install the .mobileconfig with the profiles command
/usr/bin/profiles -I -F $INSTALL_PATH

if [ $? == 0 ]; then
    echo "Successfully installed. Deleting local file..."
    rm -f $INSTALL_PATH
    exit 0
else
    echo "Installation of profile failed. Deleting local file..."
    rm -f $INSTALL_PATH
    exit 1
fi
